version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pos
      MYSQL_USER: apotheddy
      MYSQL_PASSWORD: 1234

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Sql@Secure@Password
    volumes:
      - sql-server-data:/var/opt/mssql/

volumes:
  sql-server-data:
    driver: local
